---
- name: Install Fluentd
  hosts: fluentd
  become: true
  vars:
    elasticsearch_host: "{{ hostvars[inventory_hostname]['elasticsearch_ip'] }}" # Replace with the Elasticsearch IP
    elasticsearch_port: "9200"
    fluentd_port: "24224"

  tasks:
    - name: Install dependencies
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop:
        - tar
        - gcc
        - gcc-c++
        - make


    - name: Install Fluentd using the Treasure Data script
      ansible.builtin.shell: >
        curl -fsSL https://toolbelt.treasuredata.com/sh/install-amazon2023-fluent-package5-lts.sh | sh

    - name: Install Fluentd (td-agent)
      ansible.builtin.yum:
        name: td-agent
        state: present


    - name: Configure Fluentd to accept logs from Fluent Bit and forward to Elasticsearch
      ansible.builtin.copy:
        dest: /etc/fluent/fluentd.conf
        content: |
          # Fluentd configuration to accept logs from Fluent Bit and forward to Elasticsearch
          <source>
            @type forward
            port {{ fluentd_port }}
            bind 0.0.0.0
          </source>
          <match **>
            @type elasticsearch
            host {{ elasticsearch_host }}
            port {{ elasticsearch_port }}
            logstash_format true
            include_tag_key true
            type_name fluentd
            logstash_prefix fluentd
          </match>
        mode: '0644'

    - name: Start and enable Fluentd (td-agent) service
      ansible.builtin.systemd:
        name: fluentd
        enabled: true
        state: started
