---
- name: Install Kibana
  hosts: kibana
  become: yes

  tasks:
    - name: Install Kibana GPG key
      ansible.builtin.yum:
        name: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Kibana repository
      ansible.builtin.yum_repository:
        name: elastic-7.x
        description: "Elastic repository for 7.x packages"
        baseurl: https://artifacts.elastic.co/packages/7.x/yum
        gpgcheck: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: yes

    - name: Install Kibana
      ansible.builtin.yum:
        name: kibana
        state: present

    - name: Configure Kibana to connect to Elasticsearch
      ansible.builtin.copy:
        dest: /etc/kibana/kibana.yml
        content: |
          server.host: "0.0.0.0"
          elasticsearch.hosts: ["http://{{ hostvars[inventory_hostname]['elasticsearch_ip'] }}:9200"]
        owner: kibana
        group: kibana
        mode: '0644'
      notify: Restart Kibana

    - name: Enable and start Kibana service
      ansible.builtin.systemd:
        name: kibana
        enabled: yes
        state: started

  handlers:
    - name: Restart Kibana
      ansible.builtin.systemd:
        name: kibana
        state: restarted
