---
- name: Install Node Exporter on Linux Servers
  hosts: node
  become: true

  tasks:
    - name: Create YUM repository configuration for Fluent Bit
      ansible.builtin.yum_repository:
        name: fluent-bit
        description: Fluent Bit
        baseurl: https://packages.fluentbit.io/amazonlinux/2023/
        gpgcheck: true
        gpgkey: https://packages.fluentbit.io/fluentbit.key
        enabled: true

    - name: Install Fluent Bit package
      ansible.builtin.yum:
        name: fluent-bit
        state: present

    - name: Start and enable Fluent Bit service
      ansible.builtin.systemd:
        name: fluent-bit
        enabled: true
        state: started

